[package]
name = "StringArt"
version = "1.0.1"
edition = "2024"

authors = ["epiglottis <epiglottis.cartilage@gmail.com>", "halfmonty"]
license = "MIT"

[dependencies]
image = "*"
clap = { version = "*", features = ["derive"] }
glam = "*"
rayon = "*"
rand = "*"